sil5_vitrine_accueil:
    path:     /accueil/{name}
    defaults: { _controller: sil5VitrineBundle:Default:index, name: "visiteur" }

sil5_vitrine_mentions:
    path:     /mentions-legales
    defaults: { _controller: sil5VitrineBundle:Default:mentions }

sil5_vitrine_catalogue:
    path:     /catalogue
    defaults: { _controller: sil5VitrineBundle:Default:catalogue }
