sil16_admin:
    resource: "@sil16AdminBundle/Resources/config/routing.yml"
    prefix:   /admin

sil16_vitrine:
    resource: "@sil16VitrineBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# login:
#   pattern: /login
#   defaults: { _controller: sil16VitrineBundle:Security:connexion }
# connexion_check:
#   pattern: /connexion_check
# logout:
#   pattern: /deconnexion
