# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
    access_denied_url: /render
    encoders:
        sil16\VitrineBundle\Entity\Customer:
            algorithm: bcrypt
            cost: 12
    role_hierarchy:
         ROLE_ADMIN: ROLE_CUSTOMER

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        customers:
            entity: { class: sil16VitrineBundle:Customer, property: email }

    firewalls:
        vitrine_area:
            pattern: ^/
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
            logout:
                path: /logout
                target: /login

        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/mon-compte, roles: ROLE_CUSTOMER }
