sil16\VitrineBundle\Entity\Commande:
  type: entity
  repositoryClass: sil16\VitrineBundle\Entity\CommandeRepository
  table: commande
  id:
    id:
      type: integer
      generator: { strategy: AUTO }

  fields:
    created_at:
      type: datetime
      columnDefinition: TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    state:
      type: string
  manyToOne:
    customer:
      targetEntity: Customer
      inversedBy: commandes
      joinColumn:
        name: customer_id
        referencedColumnName: id
  oneToMany:
    order_lines:
      targetEntity: OrderLine
      mappedBy: commande
