sil16\VitrineBundle\Entity\Customer:
  type: entity
  table: customer
  id:
    id:
      type: integer
      generator: { strategy: AUTO }

  fields:
    firstname:
      type: string
      length: 100
    lastname:
      type: string
      length: 100
    email:
      type: string
      length: 100
    password:
      type: string
      length: 60


  oneToMany:
    orders:
      targetEntity: Order
      mappedBy: customer
