sil16\VitrineBundle\Entity\ProductCategory:
  type: entity
  table: product_category
  id:
    id:
      type: integer
      generator: { strategy: AUTO }

  fields:
    name:
      type: string
      length: 100

  oneToMany:
    products:
      targetEntity: Product
      mappedBy: product_category
