sil16\VitrineBundle\Entity\Product:
  type: entity
  repositoryClass: sil16\VitrineBundle\Entity\ProductRepository
  table: product
  id:
    id:
      type: integer
      generator: { strategy: AUTO }

  fields:
    name:
      type: string
      length: 100
    price:
      type: decimal
      scale: 2
    description:
      type: text
      nullable: true
    stock:
      type: integer
    active:
      type: boolean
      default: true

  manyToOne:
    product_category:
      targetEntity: ProductCategory
      inversedBy: products
      joinColumn:
        name: product_category_id
        referencedColumnName: id
  oneToMany:
    pictures:
      targetEntity: Picture
      mappedBy: product
