render_with_access_denied_errors:
  path: /render/{message}/{route}
  defaults: { _controller: sil16VitrineBundle:Default:renderWithAccessDeniedErrors, message: "Vous n'êtes pas autorisé à accéder à cette page", route: 'sil16_vitrine_accueil' }

# STATIC PAGES
sil16_vitrine_accueil:
    path:     /
    defaults: { _controller: sil16VitrineBundle:Default:index, name: "visiteur" }

sil16_vitrine_mentions:
    path:     /mentions-legales
    defaults: { _controller: sil16VitrineBundle:Default:mentions }

### CUSTOMER SESSION ###########################################################
# INSCRIPTION
sil16_vitrine_subscription:
    path:     /inscription
    defaults: { _controller: sil16VitrineBundle:Registration:new }

# CONNEXION
login:
    path:     /login
    defaults: { _controller: sil16VitrineBundle:Security:logIn }

# DECONNEXION
logout:
  path: /logout

### CATALOGUE ##################################################################
# CATEGORIES
sil16_vitrine_catalogue:
    path:     /catalogue
    defaults: { _controller: sil16VitrineBundle:ProductCategory:index }

# PRODUCTS
sil16_vitrine_articles_par_categorie:
    path:     /catalogue/{product_category_id}
    defaults: { _controller: sil16VitrineBundle:Product:index }
sil16_vitrine_articles_best_sell:
    path:     /catalogue/bestSell
    defaults: { _controller: sil16VitrineBundle:Product:bestSell }


### BASKET #####################################################################
# BASKET
sil16_vitrine_basket_index:
    path:     /mon-panier
    defaults: { _controller: sil16VitrineBundle:Basket:index }
sil16_vitrine_basket_content:
    path:     /mon-panier/content
    defaults: { _controller: sil16VitrineBundle:Basket:getContent }
sil16_vitrine_basket_add_product:
    path:     /mon-panier/add_product
    defaults: { _controller: sil16VitrineBundle:Basket:addProduct }
sil16_vitrine_basket_delete_product:
    path:     /mon-panier/delete_product/{product_id}
    defaults: { _controller: sil16VitrineBundle:Basket:deleteProduct }
sil16_vitrine_basket_clear:
    path:     /mon-panier/clear
    defaults: { _controller: sil16VitrineBundle:Basket:clear }

# COMMANDES
sil16_vitrine_commande_create:
    path:     /mon-compte/mes-commandes/create
    defaults: { _controller: sil16VitrineBundle:Commande:create }
sil16_vitrine_commande_index:
    path:     /mon-compte/mes-commandes
    defaults: { _controller: sil16VitrineBundle:Commande:index }
sil16_vitrine_commande_show:
    path:     /mon-compte/mes-commandes/{commande_id}}
    defaults: { _controller: sil16VitrineBundle:Commande:show }
