# STATIC PAGES
sil16_vitrine_accueil:
    path:     /accueil/{name}
    defaults: { _controller: sil16VitrineBundle:Default:index, name: "visiteur" }

sil16_vitrine_mentions:
    path:     /mentions-legales
    defaults: { _controller: sil16VitrineBundle:Default:mentions }

### CATALOGUE ##################################################################
# CATEGORIES
sil16_vitrine_catalogue:
    path:     /catalogue
    defaults: { _controller: sil16VitrineBundle:ProductCategory:index }

# PRODUCTS
sil16_vitrine_articles_par_categorie:
    path:     /catalogue/{product_category_id}
    defaults: { _controller: sil16VitrineBundle:Product:index, product_category_id: "1" }

# BASKET
sil16_vitrine_basket_index:
    path:     /mon-panier
    defaults: { _controller: sil16VitrineBundle:Basket:index }
sil16_vitrine_basket_add_product:
    path:     /mon-panier/add_product
    defaults: { _controller: sil16VitrineBundle:Basket:addProduct }
sil16_vitrine_basket_delete_product:
    path:     /mon-panier/delete_product/{product_id}
    defaults: { _controller: sil16VitrineBundle:Basket:deleteProduct }
