# STATIC PAGES
sil16_vitrine_accueil:
    path:     /accueil/{name}
    defaults: { _controller: sil16VitrineBundle:Default:index, name: "visiteur" }

sil16_vitrine_mentions:
    path:     /mentions-legales
    defaults: { _controller: sil16VitrineBundle:Default:mentions }

### CUSTOMER SESSION ###########################################################
# INSCRIPTION
sil16_vitrine_subscription:
    path:     /inscription
    defaults: { _controller: sil16VitrineBundle:Customer:new }

# CONNEXION
sil16_vitrine_login:
    path:     /connexion
    defaults: { _controller: sil16VitrineBundle:Customer:logIn }

# DECONNEXION
sil16_vitrine_logout:
    path:     /deconnexion
    defaults: { _controller: sil16VitrineBundle:Customer:destroyCustomerSession }

### CATALOGUE ##################################################################
# CATEGORIES
sil16_vitrine_catalogue:
    path:     /catalogue
    defaults: { _controller: sil16VitrineBundle:ProductCategory:index }

# PRODUCTS
sil16_vitrine_articles_par_categorie:
    path:     /catalogue/{product_category_id}
    defaults: { _controller: sil16VitrineBundle:Product:index, product_category_id: "1" }

### BASKET #####################################################################
# BASKET
sil16_vitrine_basket_index:
    path:     /mon-panier
    defaults: { _controller: sil16VitrineBundle:Basket:index }
sil16_vitrine_basket_add_product:
    path:     /mon-panier/add_product
    defaults: { _controller: sil16VitrineBundle:Basket:addProduct }
sil16_vitrine_basket_delete_product:
    path:     /mon-panier/delete_product/{product_id}
    defaults: { _controller: sil16VitrineBundle:Basket:deleteProduct }
sil16_vitrine_basket_clear:
    path:     /mon-panier/clear
    defaults: { _controller: sil16VitrineBundle:Basket:clear }

# ORDER
sil16_vitrine_order_create:
    path:     /mon-panier/create
    defaults: { _controller: sil16VitrineBundle:Order:create }
