### ADMIN SESSION ###########################################################
sil16_vitrine_productcategory:
    resource: "@sil16AdminBundle/Resources/config/routing/product_category.yml"
    prefix:   /categories

# DASHBOARD
admin_dashboard:
    path:     /
    defaults: { _controller: sil16AdminBundle:Default:index }

# CONNEXION
admin_login:
    path:     /connexion
    defaults: { _controller: sil16AdminBundle:Admin:logIn }

# DECONNEXION
admin_logout:
    path:     /deconnexion
    defaults: { _controller: sil16AdminBundle:Admin:destroyAdminSession }

# DASHBOARD
