### ADMIN SESSION ###########################################################
sil16_admin_product_category:
    resource: "@sil16AdminBundle/Resources/config/routing/product_category.yml"
    prefix:   /categories

sil16_admin_product:
    resource: "@sil16AdminBundle/Resources/config/routing/product.yml"
    prefix:   /produits

sil16_admin_commande:
    resource: "@sil16AdminBundle/Resources/config/routing/commande.yml"
    prefix:   /commandes

# DASHBOARD - ACCUEIL (simple)
admin_dashboard:
    path:     /
    defaults: { _controller: sil16AdminBundle:Default:index }
