### ADMIN SESSION ###########################################################
sil16_admin_product_category:
    resource: "@sil16AdminBundle/Resources/config/routing/product_category.yml"
    prefix:   /categories

sil16_admin_product:
    resource: "@sil16AdminBundle/Resources/config/routing/product.yml"
    prefix:   /produits

# DASHBOARD
admin_dashboard:
    path:     /
    defaults: { _controller: sil16AdminBundle:Default:index }

# CONNEXION
admin_login:
    path:     /connexion
    defaults: { _controller: sil16AdminBundle:Admin:logIn }

# DECONNEXION
admin_logout:
    path:     /deconnexion
    defaults: { _controller: sil16AdminBundle:Admin:destroyAdminSession }

# DASHBOARD
