admin_product_index:
    path:     /
    defaults: { _controller: "sil16AdminBundle:Product:index" }
    methods:  GET

admin_product_new:
    path:     /new
    defaults: { _controller: "sil16AdminBundle:Product:new" }
    methods:  [GET, POST]

admin_product_edit:
    path:     /{id}/edit
    defaults: { _controller: "sil16AdminBundle:Product:edit" }
    methods:  [GET, POST]

admin_product_delete:
    path:     /{id}/delete
    defaults: { _controller: "sil16AdminBundle:Product:delete" }
    methods:  DELETE

admin_toggle_active:
  path:   /{id}/toggle
  defaults: { _controller: "sil16AdminBundle:Product:toggleActive"}
