<?php

namespace sil16\VitrineBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeRepository extends EntityRepository
{
  public function findByUserOrderedByCreatedAt($customer_id, $order="DESC") {
      $qb = $this->createQueryBuilder('c');
      return $qb->join('c.customer', 'cust', 'WITH', 'cust.id = :customer_id')
                ->setParameter('customer_id', $customer_id)
                ->orderBy('c.created_at', $order)
                ->getQuery()
                ->getResult();
    }

      public function findAllOrderedByCreatedAt($order="DESC") {
          $qb = $this->createQueryBuilder('c');
          return $qb->orderBy('c.created_at', $order)
                    ->getQuery()
                    ->getResult();
        }
}
